In [1]:
import threading
import numpy as np
import time

Matrix_A = []
Matrix_B = []
Matrix_C = []

def Input_for_matrix_dimensions():
    """Function to take the dimensional input from the user."""
    global A_row, A_col, B_row, B_col, num_of_threads, V
    A_row = int(input("Enter the number of rows in the first matrix: "))
    A_col = int(input("Enter the number of columns in the first matrix: "))
    B_row = int(input("Enter the number of rows in the second matrix: "))
    B_col = int(input("Enter the number of columns in the second matrix: "))
    V = int(input("Do you want to see the verbose? (1 for yes, 0 for no): "))

    # Ensure the matrices can be multiplied
    if A_col != B_row:
        print("Matrix multiplication is not possible with these dimensions. Exiting.")
        exit()

    # Number of threads equals the number of rows in the solution matrix C, which is the same as A_row
    num_of_threads = A_row

def Initialize_Matrix():
    """Function to initialize the matrices by populating them with random numbers from 1 to 10."""
    global Matrix_A, Matrix_B, Matrix_C
    Matrix_A = np.random.randint(10, size=(A_row, A_col))
    Matrix_B = np.random.randint(10, size=(B_row, B_col))
    Matrix_C = np.zeros((A_row, B_col)).astype(int)

def Matrix_multiply_parallel(row, z):
    """Performs multiplication for a specific row using a thread."""
    global Matrix_A, Matrix_B, Matrix_C
    for i in range(B_col):
        for j in range(A_col):
            Matrix_C[z][i] += int(row[j] * Matrix_B[j][i])

def Thread_function():
    """Function for the creation and execution of row threads."""
    global num_of_threads
    threads = []

    # Create and execute threads for each row
    for j in range(num_of_threads):
        t = threading.Thread(target=Matrix_multiply_parallel, args=(Matrix_A[j], j))
        threads.append(t)
        t.start()

    # Wait for all threads to complete
    for t in threads:
        t.join()

if __name__ == "__main__":
    """Driver Code"""
    Input_for_matrix_dimensions()
    Initialize_Matrix()

    # Parallel matrix multiplication using threads
    start_time = time.time()
    Thread_function()
    end_time = time.time()
    print("Time taken to multiply two matrices in parallel:", round(end_time - start_time, 5), "seconds")

    # Sequential matrix multiplication
    result = np.zeros((A_row, B_col)).astype(int)
    start_time = time.time()

    # Iterating by row of Matrix_A
    for i in range(A_row):
        # Iterating by column of Matrix_B
        for j in range(B_col):
            # Iterating by rows of Matrix_B
            for k in range(B_row):
                result[i][j] += Matrix_A[i][k] * Matrix_B[k][j]

    end_time = time.time()
    print("Time taken to multiply two matrices sequentially:", round(end_time - start_time, 5), "seconds")

    # If verbose is enabled, print matrices and result comparison
    if V:
        if np.array_equal(result, Matrix_C):
            print("Matrices multiplied successfully. Result:")
            print(Matrix_C, "\n")
            print("Matrix A:\n", Matrix_A, "\n")
            print("Matrix B:\n", Matrix_B, "\n")
        else:
            print("Error: Matrices did not multiply correctly.")



Enter the number of rows in the first matrix:  4
Enter the number of columns in the first matrix:  4
Enter the number of rows in the second matrix:  4
Enter the number of columns in the second matrix:  3
Do you want to see the verbose? (1 for yes, 0 for no):  1


Time taken to multiply two matrices in parallel: 0.00602 seconds
Time taken to multiply two matrices sequentially: 0.0 seconds
Matrices multiplied successfully. Result:
[[ 42  53  66]
 [106  79  62]
 [130 112 101]
 [ 68  61  61]] 

Matrix A:
 [[9 0 7 1]
 [7 9 1 1]
 [4 9 7 7]
 [9 4 4 0]] 

Matrix B:
 [[4 5 5]
 [8 4 2]
 [0 0 2]
 [6 8 7]] 

